version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: timesheet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: timesheetintegration
    ports:
      - "3307:3306"  # Changed from 3306:3306 to avoid conflict
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - timesheet-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s

  # Spring Boot Backend
  backend:
    build: ./Timesheet-Client-monolithic-arch
    container_name: timesheet-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/timesheetintegration?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    ports:
      - "0.0.0.0:8083:8083"  # Listen on all interfaces
    networks:
      - timesheet-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Angular Frontend
  frontend:
    build: ./Timesheet_FrontEnd
    container_name: timesheet-frontend
    depends_on:
      - backend
    environment:
      - API_HOST=${HOST_IP:-localhost}  # Use HOST_IP environment variable or localhost as fallback
    ports:
      - "0.0.0.0:4200:80"  # Changed from 8080 to 4200 to avoid Jenkins conflict
    networks:
      - timesheet-network

  # Nginx Exporter for Frontend metrics
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: timesheet-nginx-exporter
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://frontend:80/nginx_status'
    depends_on:
      - frontend
    networks:
      - timesheet-network
    restart: unless-stopped

  # Prometheus for Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: timesheet-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - timesheet-network

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: timesheet-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - timesheet-network

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: timesheet-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - timesheet-network
    restart: unless-stopped

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
  jenkins_data:

networks:
  timesheet-network:
    driver: bridge
