global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'timesheet-backend'
    static_configs:
      - targets: ['backend:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  # Node/system metrics via node_exporter  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
  # Frontend nginx metrics via nginx-prometheus-exporter
  - job_name: 'frontend-nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 10s
