global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'timesheet-backend'
    static_configs:
      - targets: ['backend:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
